//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.05 at 12:17:15 PM CET
//

package sk.itcloud.maven.model.form;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import eu.livotov.labs.vaadin.autoforms.ann.FormBean;
import eu.livotov.labs.vaadin.autoforms.ann.FormField;

@FormBean(rows = 5, columns = 2, cancelButtonVisible = false, commitButtonVisible = false, title = "Build Settings")
public class Build implements Serializable
{

	@FormField(title = "Source Directory", location = "0,0", required = true, requiredFieldErrorMessage = "Please enter connection")
	protected String sourceDirectory;

	@FormField(title = "Script Source Directory", location = "0,1", required = true, requiredFieldErrorMessage = "Please enter connection")
	protected String scriptSourceDirectory;

	@FormField(title = "Output Directory", location = "0,2", required = true, requiredFieldErrorMessage = "Please enter connection")
	protected String outputDirectory;

	@FormField(title = "Directory", location = "0,3", required = true, requiredFieldErrorMessage = "Please enter connection")
	protected String directory;

	protected Build.Extensions extensions;

	@FormField(title = "Default Goal", location = "0,4", required = true, requiredFieldErrorMessage = "Please enter connection")
	protected String defaultGoal;

	protected Build.Resources resources;
	protected Build.TestResources testResources;

	@FormField(title = "Final Name", location = "1,0", required = true, requiredFieldErrorMessage = "Please enter connection")
	protected String finalName;

	@FormField(title = "Test Source Directory", location = "1,1", required = true, requiredFieldErrorMessage = "Please enter connection")
	protected String testSourceDirectory;

	@FormField(title = "Test Output Directory", location = "1,2", required = true, requiredFieldErrorMessage = "Please enter connection")
	protected String testOutputDirectory;

	protected Build.Filters filters;
	protected PluginManagement pluginManagement;
	protected Build.Plugins plugins;

	/**
	 * Gets the value of the sourceDirectory property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSourceDirectory()
	{
		return sourceDirectory;
	}

	/**
	 * Sets the value of the sourceDirectory property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSourceDirectory(String value)
	{
		this.sourceDirectory = value;
	}

	/**
	 * Gets the value of the scriptSourceDirectory property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getScriptSourceDirectory()
	{
		return scriptSourceDirectory;
	}

	/**
	 * Sets the value of the scriptSourceDirectory property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setScriptSourceDirectory(String value)
	{
		this.scriptSourceDirectory = value;
	}

	/**
	 * Gets the value of the testSourceDirectory property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTestSourceDirectory()
	{
		return testSourceDirectory;
	}

	/**
	 * Sets the value of the testSourceDirectory property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTestSourceDirectory(String value)
	{
		this.testSourceDirectory = value;
	}

	/**
	 * Gets the value of the outputDirectory property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOutputDirectory()
	{
		return outputDirectory;
	}

	/**
	 * Sets the value of the outputDirectory property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOutputDirectory(String value)
	{
		this.outputDirectory = value;
	}

	/**
	 * Gets the value of the testOutputDirectory property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTestOutputDirectory()
	{
		return testOutputDirectory;
	}

	/**
	 * Sets the value of the testOutputDirectory property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTestOutputDirectory(String value)
	{
		this.testOutputDirectory = value;
	}

	/**
	 * Gets the value of the extensions property.
	 * 
	 * @return possible object is {@link Build.Extensions }
	 * 
	 */
	public Build.Extensions getExtensions()
	{
		return extensions;
	}

	/**
	 * Sets the value of the extensions property.
	 * 
	 * @param value
	 *            allowed object is {@link Build.Extensions }
	 * 
	 */
	public void setExtensions(Build.Extensions value)
	{
		this.extensions = value;
	}

	/**
	 * Gets the value of the defaultGoal property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDefaultGoal()
	{
		return defaultGoal;
	}

	/**
	 * Sets the value of the defaultGoal property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDefaultGoal(String value)
	{
		this.defaultGoal = value;
	}

	/**
	 * Gets the value of the resources property.
	 * 
	 * @return possible object is {@link Build.Resources }
	 * 
	 */
	public Build.Resources getResources()
	{
		return resources;
	}

	/**
	 * Sets the value of the resources property.
	 * 
	 * @param value
	 *            allowed object is {@link Build.Resources }
	 * 
	 */
	public void setResources(Build.Resources value)
	{
		this.resources = value;
	}

	/**
	 * Gets the value of the testResources property.
	 * 
	 * @return possible object is {@link Build.TestResources }
	 * 
	 */
	public Build.TestResources getTestResources()
	{
		return testResources;
	}

	/**
	 * Sets the value of the testResources property.
	 * 
	 * @param value
	 *            allowed object is {@link Build.TestResources }
	 * 
	 */
	public void setTestResources(Build.TestResources value)
	{
		this.testResources = value;
	}

	/**
	 * Gets the value of the directory property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDirectory()
	{
		return directory;
	}

	/**
	 * Sets the value of the directory property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDirectory(String value)
	{
		this.directory = value;
	}

	/**
	 * Gets the value of the finalName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFinalName()
	{
		return finalName;
	}

	/**
	 * Sets the value of the finalName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFinalName(String value)
	{
		this.finalName = value;
	}

	/**
	 * Gets the value of the filters property.
	 * 
	 * @return possible object is {@link Build.Filters }
	 * 
	 */
	public Build.Filters getFilters()
	{
		return filters;
	}

	/**
	 * Sets the value of the filters property.
	 * 
	 * @param value
	 *            allowed object is {@link Build.Filters }
	 * 
	 */
	public void setFilters(Build.Filters value)
	{
		this.filters = value;
	}

	/**
	 * Gets the value of the pluginManagement property.
	 * 
	 * @return possible object is {@link PluginManagement }
	 * 
	 */
	public PluginManagement getPluginManagement()
	{
		return pluginManagement;
	}

	/**
	 * Sets the value of the pluginManagement property.
	 * 
	 * @param value
	 *            allowed object is {@link PluginManagement }
	 * 
	 */
	public void setPluginManagement(PluginManagement value)
	{
		this.pluginManagement = value;
	}

	/**
	 * Gets the value of the plugins property.
	 * 
	 * @return possible object is {@link Build.Plugins }
	 * 
	 */
	public Build.Plugins getPlugins()
	{
		return plugins;
	}

	/**
	 * Sets the value of the plugins property.
	 * 
	 * @param value
	 *            allowed object is {@link Build.Plugins }
	 * 
	 */
	public void setPlugins(Build.Plugins value)
	{
		this.plugins = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="extension" type="{http://maven.apache.org/POM/4.0.0}Extension" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Extensions
	{

		protected List<Extension> extension;

		/**
		 * Gets the value of the extension property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the extension property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getExtension().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Extension }
		 * 
		 * 
		 */
		public List<Extension> getExtension()
		{
			if (extension == null)
			{
				extension = new ArrayList<Extension>();
			}
			return this.extension;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="filter" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Filters
	{

		protected List<String> filter;

		/**
		 * Gets the value of the filter property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the filter property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getFilter().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link String }
		 * 
		 * 
		 */
		public List<String> getFilter()
		{
			if (filter == null)
			{
				filter = new ArrayList<String>();
			}
			return this.filter;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="plugin" type="{http://maven.apache.org/POM/4.0.0}Plugin" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Plugins
	{

		protected List<Plugin> plugin;

		/**
		 * Gets the value of the plugin property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the plugin property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getPlugin().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Plugin }
		 * 
		 * 
		 */
		public List<Plugin> getPlugin()
		{
			if (plugin == null)
			{
				plugin = new ArrayList<Plugin>();
			}
			return this.plugin;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="resource" type="{http://maven.apache.org/POM/4.0.0}Resource" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Resources
	{

		protected List<Resource> resource;

		/**
		 * Gets the value of the resource property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the resource property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getResource().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Resource }
		 * 
		 * 
		 */
		public List<Resource> getResource()
		{
			if (resource == null)
			{
				resource = new ArrayList<Resource>();
			}
			return this.resource;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="testResource" type="{http://maven.apache.org/POM/4.0.0}Resource" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class TestResources
	{

		protected List<Resource> testResource;

		/**
		 * Gets the value of the testResource property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the testResource property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getTestResource().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Resource }
		 * 
		 * 
		 */
		public List<Resource> getTestResource()
		{
			if (testResource == null)
			{
				testResource = new ArrayList<Resource>();
			}
			return this.testResource;
		}

	}

}
