//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.05 at 12:17:15 PM CET
//

package sk.itcloud.maven.model.form;

import java.io.Serializable;

import java.util.ArrayList;
import java.util.List;

import eu.livotov.labs.vaadin.autoforms.ann.FormBean;
import eu.livotov.labs.vaadin.autoforms.ann.FormField;

@FormBean(rows = 4, columns = 2, cancelButtonVisible = false, commitButtonVisible = false, title = "Dependency")
public class Dependency implements Serializable
{

	@FormField(title = "Group Id", location = "0,0", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String groupId;

	@FormField(title = "Artifact Id", location = "0,1", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String artifactId;

	@FormField(title = "Version", location = "0,2", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String version;

	@FormField(title = "Type", location = "0,3", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String type = "jar";

	@FormField(title = "Classifier", location = "1,0", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String classifier;

	@FormField(title = "Scope", location = "1,1", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String scope;

	@FormField(title = "System Path", location = "1,2", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String systemPath;

	protected Dependency.Exclusions exclusions;

	@FormField(title = "optional", location = "1,3", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String optional;

	/**
	 * Gets the value of the groupId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGroupId()
	{
		return groupId;
	}

	/**
	 * Sets the value of the groupId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGroupId(String value)
	{
		this.groupId = value;
	}

	/**
	 * Gets the value of the artifactId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArtifactId()
	{
		return artifactId;
	}

	/**
	 * Sets the value of the artifactId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArtifactId(String value)
	{
		this.artifactId = value;
	}

	/**
	 * Gets the value of the version property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVersion()
	{
		return version;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVersion(String value)
	{
		this.version = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType()
	{
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value)
	{
		this.type = value;
	}

	/**
	 * Gets the value of the classifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClassifier()
	{
		return classifier;
	}

	/**
	 * Sets the value of the classifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClassifier(String value)
	{
		this.classifier = value;
	}

	/**
	 * Gets the value of the scope property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getScope()
	{
		return scope;
	}

	/**
	 * Sets the value of the scope property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setScope(String value)
	{
		this.scope = value;
	}

	/**
	 * Gets the value of the systemPath property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSystemPath()
	{
		return systemPath;
	}

	/**
	 * Sets the value of the systemPath property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSystemPath(String value)
	{
		this.systemPath = value;
	}

	/**
	 * Gets the value of the exclusions property.
	 * 
	 * @return possible object is {@link Dependency.Exclusions }
	 * 
	 */
	public Dependency.Exclusions getExclusions()
	{
		return exclusions;
	}

	/**
	 * Sets the value of the exclusions property.
	 * 
	 * @param value
	 *            allowed object is {@link Dependency.Exclusions }
	 * 
	 */
	public void setExclusions(Dependency.Exclusions value)
	{
		this.exclusions = value;
	}

	/**
	 * Gets the value of the optional property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOptional()
	{
		return optional;
	}

	/**
	 * Sets the value of the optional property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOptional(String value)
	{
		this.optional = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="exclusion" type="{http://maven.apache.org/POM/4.0.0}Exclusion" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Exclusions
	{

		protected List<Exclusion> exclusion;

		/**
		 * Gets the value of the exclusion property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the exclusion property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getExclusion().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Exclusion }
		 * 
		 * 
		 */
		public List<Exclusion> getExclusion()
		{
			if (exclusion == null)
			{
				exclusion = new ArrayList<Exclusion>();
			}
			return this.exclusion;
		}

	}

}
