//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.05 at 12:17:15 PM CET
//

package sk.itcloud.maven.model.form;

import java.util.ArrayList;
import java.util.List;
import eu.livotov.labs.vaadin.autoforms.ann.FormBean;
import eu.livotov.labs.vaadin.autoforms.ann.FormField;

@FormBean(rows = 4, columns = 3, cancelButtonVisible = false, commitButtonVisible = false, title = "Developer")
public class Developer
{
	@FormField(title = "Id", location = "0,0", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String id;

	@FormField(title = "Name", location = "0,1", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String name;

	@FormField(title = "Email", location = "0,2", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String email;

	@FormField(title = "Url", location = "0,3", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String url;

	@FormField(title = "Orgranization", location = "1,0", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String organization;

	@FormField(title = "Orgranization Url", location = "1,1", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String organizationUrl;

	protected Developer.Roles roles;

	@FormField(title = "Timezone", location = "1,2", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String timezone;

	protected Developer.Properties properties;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value)
	{
		this.id = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the email property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEmail()
	{
		return email;
	}

	/**
	 * Sets the value of the email property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEmail(String value)
	{
		this.email = value;
	}

	/**
	 * Gets the value of the url property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUrl()
	{
		return url;
	}

	/**
	 * Sets the value of the url property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUrl(String value)
	{
		this.url = value;
	}

	/**
	 * Gets the value of the organization property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOrganization()
	{
		return organization;
	}

	/**
	 * Sets the value of the organization property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOrganization(String value)
	{
		this.organization = value;
	}

	/**
	 * Gets the value of the organizationUrl property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOrganizationUrl()
	{
		return organizationUrl;
	}

	/**
	 * Sets the value of the organizationUrl property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOrganizationUrl(String value)
	{
		this.organizationUrl = value;
	}

	/**
	 * Gets the value of the roles property.
	 * 
	 * @return possible object is {@link Developer.Roles }
	 * 
	 */
	public Developer.Roles getRoles()
	{
		return roles;
	}

	/**
	 * Sets the value of the roles property.
	 * 
	 * @param value
	 *            allowed object is {@link Developer.Roles }
	 * 
	 */
	public void setRoles(Developer.Roles value)
	{
		this.roles = value;
	}

	/**
	 * Gets the value of the timezone property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTimezone()
	{
		return timezone;
	}

	/**
	 * Sets the value of the timezone property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTimezone(String value)
	{
		this.timezone = value;
	}

	/**
	 * Gets the value of the properties property.
	 * 
	 * @return possible object is {@link Developer.Properties }
	 * 
	 */
	public Developer.Properties getProperties()
	{
		return properties;
	}

	/**
	 * Sets the value of the properties property.
	 * 
	 * @param value
	 *            allowed object is {@link Developer.Properties }
	 * 
	 */
	public void setProperties(Developer.Properties value)
	{
		this.properties = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Properties
	{

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Roles
	{

		protected List<String> role;

		/**
		 * Gets the value of the role property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the role property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getRole().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link String }
		 * 
		 * 
		 */
		public List<String> getRole()
		{
			if (role == null)
			{
				role = new ArrayList<String>();
			}
			return this.role;
		}

	}

}
