//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.05 at 12:17:15 PM CET
//

package sk.itcloud.maven.model.form;

import java.io.Serializable;
import eu.livotov.labs.vaadin.autoforms.ann.FormBean;
import eu.livotov.labs.vaadin.autoforms.ann.FormField;

@FormBean(rows = 2, columns = 2, cancelButtonVisible = false, commitButtonVisible = false, title = "Issue Management")
public class IssueManagement implements Serializable
{

	@FormField(title = "System", location = "1,0", required = true, requiredFieldErrorMessage = "Please enter Issue Management system")
	protected String system;

	@FormField(title = "URL", location = "1,1", required = true, requiredFieldErrorMessage = "Please enter Issue Management url")
	protected String url;

	/**
	 * Gets the value of the system property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSystem()
	{
		return system;
	}

	/**
	 * Sets the value of the system property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSystem(String value)
	{
		this.system = value;
	}

	/**
	 * Gets the value of the url property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUrl()
	{
		return url;
	}

	/**
	 * Sets the value of the url property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUrl(String value)
	{
		this.url = value;
	}

}
