//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.05 at 12:17:15 PM CET
//

package sk.itcloud.maven.model.form;

import eu.livotov.labs.vaadin.autoforms.ann.FormBean;
import eu.livotov.labs.vaadin.autoforms.ann.FormField;

@FormBean(rows = 2, columns = 2, cancelButtonVisible = false, commitButtonVisible = false, title = "License")
public class License
{

	@FormField(title = "Name", location = "0,0", required = true, requiredFieldErrorMessage = "Please enter")
	protected String name;

	@FormField(title = "Url", location = "0,1", required = true, requiredFieldErrorMessage = "Please enter")
	protected String url;

	@FormField(title = "Distribution", location = "1,0", required = true, requiredFieldErrorMessage = "Please enter")
	protected String distribution;

	@FormField(title = "Comments", location = "1,1", required = true, requiredFieldErrorMessage = "Please enter")
	protected String comments;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the url property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUrl()
	{
		return url;
	}

	/**
	 * Sets the value of the url property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUrl(String value)
	{
		this.url = value;
	}

	/**
	 * Gets the value of the distribution property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDistribution()
	{
		return distribution;
	}

	/**
	 * Sets the value of the distribution property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDistribution(String value)
	{
		this.distribution = value;
	}

	/**
	 * Gets the value of the comments property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getComments()
	{
		return comments;
	}

	/**
	 * Sets the value of the comments property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setComments(String value)
	{
		this.comments = value;
	}

}
