//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.05 at 12:17:15 PM CET
//

package sk.itcloud.maven.model.form;

import java.util.ArrayList;
import java.util.List;

import eu.livotov.labs.vaadin.autoforms.ann.FormBean;
import eu.livotov.labs.vaadin.autoforms.ann.FormField;

@FormBean(rows = 5, columns = 2, cancelButtonVisible = false, commitButtonVisible = false, title = "Mailing List")
public class MailingList
{
	@FormField(title = "Name", location = "0,0", required = true, requiredFieldErrorMessage = "Please enter")
	protected String name;

	@FormField(title = "Subscribe", location = "0,1", required = true, requiredFieldErrorMessage = "Please enter")
	protected String subscribe;

	@FormField(title = "Unsubscribe", location = "0,2", required = true, requiredFieldErrorMessage = "Please enter")
	protected String unsubscribe;

	@FormField(title = "Post", location = "0,3", required = true, requiredFieldErrorMessage = "Please enter")
	protected String post;

	@FormField(title = "Archive", location = "0,4", required = true, requiredFieldErrorMessage = "Please enter")
	protected String archive;

	protected MailingList.OtherArchives otherArchives;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the subscribe property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubscribe()
	{
		return subscribe;
	}

	/**
	 * Sets the value of the subscribe property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubscribe(String value)
	{
		this.subscribe = value;
	}

	/**
	 * Gets the value of the unsubscribe property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUnsubscribe()
	{
		return unsubscribe;
	}

	/**
	 * Sets the value of the unsubscribe property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUnsubscribe(String value)
	{
		this.unsubscribe = value;
	}

	/**
	 * Gets the value of the post property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPost()
	{
		return post;
	}

	/**
	 * Sets the value of the post property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPost(String value)
	{
		this.post = value;
	}

	/**
	 * Gets the value of the archive property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArchive()
	{
		return archive;
	}

	/**
	 * Sets the value of the archive property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArchive(String value)
	{
		this.archive = value;
	}

	/**
	 * Gets the value of the otherArchives property.
	 * 
	 * @return possible object is {@link MailingList.OtherArchives }
	 * 
	 */
	public MailingList.OtherArchives getOtherArchives()
	{
		return otherArchives;
	}

	/**
	 * Sets the value of the otherArchives property.
	 * 
	 * @param value
	 *            allowed object is {@link MailingList.OtherArchives }
	 * 
	 */
	public void setOtherArchives(MailingList.OtherArchives value)
	{
		this.otherArchives = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="otherArchive" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class OtherArchives
	{

		protected List<String> otherArchive;

		/**
		 * Gets the value of the otherArchive property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the otherArchive property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getOtherArchive().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link String }
		 * 
		 * 
		 */
		public List<String> getOtherArchive()
		{
			if (otherArchive == null)
			{
				otherArchive = new ArrayList<String>();
			}
			return this.otherArchive;
		}

	}
}