//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.05 at 12:17:15 PM CET
//

package sk.itcloud.maven.model.form;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;

import eu.livotov.labs.vaadin.autoforms.ann.FormBean;
import eu.livotov.labs.vaadin.autoforms.ann.FormField;

@FormBean(rows = 5, columns = 1, cancelButtonVisible = false, commitButtonVisible = false, title = "Plugins")
public class Plugin implements Serializable
{
	@FormField(title = "Group Id", location = "0,0", required = true, requiredFieldErrorMessage = "Please enter")
	protected String groupId = "org.apache.maven.plugins";

	@FormField(title = "Artifact Id", location = "0,1", required = true, requiredFieldErrorMessage = "Please enter")
	protected String artifactId;

	@FormField(title = "Version", location = "0,2", required = true, requiredFieldErrorMessage = "Please enter")
	protected String version;

	@FormField(title = "Extensions", location = "0,3", required = true, requiredFieldErrorMessage = "Please enter")
	protected String extensions;

	protected Plugin.Executions executions;
	protected Plugin.Dependencies dependencies;
	protected Plugin.Goals goals;

	@FormField(title = "Inherited", location = "0,4", required = true, requiredFieldErrorMessage = "Please enter")
	protected String inherited;

	protected Plugin.Configuration configuration;

	/**
	 * Gets the value of the groupId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGroupId()
	{
		return groupId;
	}

	/**
	 * Sets the value of the groupId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGroupId(String value)
	{
		this.groupId = value;
	}

	/**
	 * Gets the value of the artifactId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArtifactId()
	{
		return artifactId;
	}

	/**
	 * Sets the value of the artifactId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArtifactId(String value)
	{
		this.artifactId = value;
	}

	/**
	 * Gets the value of the version property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVersion()
	{
		return version;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVersion(String value)
	{
		this.version = value;
	}

	/**
	 * Gets the value of the extensions property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExtensions()
	{
		return extensions;
	}

	/**
	 * Sets the value of the extensions property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExtensions(String value)
	{
		this.extensions = value;
	}

	/**
	 * Gets the value of the executions property.
	 * 
	 * @return possible object is {@link Plugin.Executions }
	 * 
	 */
	public Plugin.Executions getExecutions()
	{
		return executions;
	}

	/**
	 * Sets the value of the executions property.
	 * 
	 * @param value
	 *            allowed object is {@link Plugin.Executions }
	 * 
	 */
	public void setExecutions(Plugin.Executions value)
	{
		this.executions = value;
	}

	/**
	 * Gets the value of the dependencies property.
	 * 
	 * @return possible object is {@link Plugin.Dependencies }
	 * 
	 */
	public Plugin.Dependencies getDependencies()
	{
		return dependencies;
	}

	/**
	 * Sets the value of the dependencies property.
	 * 
	 * @param value
	 *            allowed object is {@link Plugin.Dependencies }
	 * 
	 */
	public void setDependencies(Plugin.Dependencies value)
	{
		this.dependencies = value;
	}

	/**
	 * Gets the value of the goals property.
	 * 
	 * @return possible object is {@link Plugin.Goals }
	 * 
	 */
	public Plugin.Goals getGoals()
	{
		return goals;
	}

	/**
	 * Sets the value of the goals property.
	 * 
	 * @param value
	 *            allowed object is {@link Plugin.Goals }
	 * 
	 */
	public void setGoals(Plugin.Goals value)
	{
		this.goals = value;
	}

	/**
	 * Gets the value of the inherited property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInherited()
	{
		return inherited;
	}

	/**
	 * Sets the value of the inherited property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInherited(String value)
	{
		this.inherited = value;
	}

	/**
	 * Gets the value of the configuration property.
	 * 
	 * @return possible object is {@link Plugin.Configuration }
	 * 
	 */
	public Plugin.Configuration getConfiguration()
	{
		return configuration;
	}

	/**
	 * Sets the value of the configuration property.
	 * 
	 * @param value
	 *            allowed object is {@link Plugin.Configuration }
	 * 
	 */
	public void setConfiguration(Plugin.Configuration value)
	{
		this.configuration = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Configuration
	{
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="dependency" type="{http://maven.apache.org/POM/4.0.0}Dependency" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Dependencies
	{

		protected List<Dependency> dependency;

		/**
		 * Gets the value of the dependency property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the dependency property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getDependency().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Dependency }
		 * 
		 * 
		 */
		public List<Dependency> getDependency()
		{
			if (dependency == null)
			{
				dependency = new ArrayList<Dependency>();
			}
			return this.dependency;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="execution" type="{http://maven.apache.org/POM/4.0.0}PluginExecution" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Executions
	{

		protected List<PluginExecution> execution;

		/**
		 * Gets the value of the execution property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the execution property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getExecution().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link PluginExecution }
		 * 
		 * 
		 */
		public List<PluginExecution> getExecution()
		{
			if (execution == null)
			{
				execution = new ArrayList<PluginExecution>();
			}
			return this.execution;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Goals
	{
	}
}