//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.05 at 12:17:15 PM CET
//

package sk.itcloud.maven.model.form;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class ReportSet implements Serializable
{

	protected String id;
	protected ReportSet.Reports reports;
	protected String inherited;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value)
	{
		this.id = value;
	}

	/**
	 * Gets the value of the reports property.
	 * 
	 * @return possible object is {@link ReportSet.Reports }
	 * 
	 */
	public ReportSet.Reports getReports()
	{
		return reports;
	}

	/**
	 * Sets the value of the reports property.
	 * 
	 * @param value
	 *            allowed object is {@link ReportSet.Reports }
	 * 
	 */
	public void setReports(ReportSet.Reports value)
	{
		this.reports = value;
	}

	/**
	 * Gets the value of the inherited property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInherited()
	{
		return inherited;
	}

	/**
	 * Sets the value of the inherited property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInherited(String value)
	{
		this.inherited = value;
	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="report" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Reports
	{

		protected List<String> report;

		/**
		 * Gets the value of the report property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the report property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getReport().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link String }
		 * 
		 * 
		 */
		public List<String> getReport()
		{
			if (report == null)
			{
				report = new ArrayList<String>();
			}
			return this.report;
		}

	}

}
