//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.05 at 12:17:15 PM CET
//

package sk.itcloud.maven.model.form;

import java.io.Serializable;
import eu.livotov.labs.vaadin.autoforms.ann.FormBean;
import eu.livotov.labs.vaadin.autoforms.ann.FormField;

@FormBean(rows = 2, columns = 2, cancelButtonVisible = false, commitButtonVisible = false, title = "Source Control Management")
public class Scm implements Serializable
{
	@FormField(title = "Connection", location = "0,0", required = true, requiredFieldErrorMessage = "Please enter connection")
	protected String connection;

	@FormField(title = "Developer Connection", location = "0,1", required = true, requiredFieldErrorMessage = "Please enter developer connection")
	protected String developerConnection;

	@FormField(title = "Tag", location = "1,0", required = true, requiredFieldErrorMessage = "Please enter tag")
	protected String tag;

	@FormField(title = "Url", location = "1,1", required = true, requiredFieldErrorMessage = "Please enter url")
	protected String url;

	/**
	 * Gets the value of the connection property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getConnection()
	{
		return connection;
	}

	/**
	 * Sets the value of the connection property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setConnection(String value)
	{
		this.connection = value;
	}

	/**
	 * Gets the value of the developerConnection property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeveloperConnection()
	{
		return developerConnection;
	}

	/**
	 * Sets the value of the developerConnection property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeveloperConnection(String value)
	{
		this.developerConnection = value;
	}

	/**
	 * Gets the value of the tag property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTag()
	{
		return tag;
	}

	/**
	 * Sets the value of the tag property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTag(String value)
	{
		this.tag = value;
	}

	/**
	 * Gets the value of the url property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUrl()
	{
		return url;
	}

	/**
	 * Sets the value of the url property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUrl(String value)
	{
		this.url = value;
	}

}
