//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.08 at 11:05:04 AM CET
//

package sk.itcloud.maven.settings.form;

import eu.livotov.labs.vaadin.autoforms.ann.FormBean;
import eu.livotov.labs.vaadin.autoforms.ann.FormField;

@FormBean(rows = 6, columns = 1, cancelButtonVisible = false, commitButtonVisible = false, title = "Mirror")
public class Mirror
{

	@FormField(title = "Mirror Of", location = "0,0", required = true, requiredFieldErrorMessage = "Please enter")
	protected String mirrorOf;

	@FormField(title = "Name", location = "0,1", required = true, requiredFieldErrorMessage = "Please enter")
	protected String name;

	@FormField(title = "Url", location = "0,2", required = true, requiredFieldErrorMessage = "Please enter")
	protected String url;

	@FormField(title = "Id", location = "0,3", required = true, requiredFieldErrorMessage = "Please enter")
	protected String id;

	/**
	 * Gets the value of the mirrorOf property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMirrorOf()
	{
		return mirrorOf;
	}

	/**
	 * Sets the value of the mirrorOf property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMirrorOf(String value)
	{
		this.mirrorOf = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the url property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUrl()
	{
		return url;
	}

	/**
	 * Sets the value of the url property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUrl(String value)
	{
		this.url = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value)
	{
		this.id = value;
	}

}
