//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.08 at 11:05:04 AM CET
//

package sk.itcloud.maven.settings.form;

import java.util.ArrayList;
import java.util.List;
import eu.livotov.labs.vaadin.autoforms.ann.FormBean;
import eu.livotov.labs.vaadin.autoforms.ann.FormField;

@FormBean(rows = 4, columns = 1, cancelButtonVisible = false, commitButtonVisible = false, title = "Settings")
public class Settings
{

	@FormField(title = "Local Repository", location = "0,0", required = true, requiredFieldErrorMessage = "Please enter ")
	protected String localRepository;

	@FormField(title = "Interactive Mode", location = "0,1", required = false, requiredFieldErrorMessage = "Please enter ")
	protected Boolean interactiveMode = true;

	@FormField(title = "Use Plugin Registry", location = "0,2", required = false, requiredFieldErrorMessage = "Please enter ")
	protected Boolean usePluginRegistry = false;

	@FormField(title = "Offline", location = "0,3", required = false, requiredFieldErrorMessage = "Please enter ")
	protected Boolean offline = false;

	protected Settings.Proxies proxies;
	protected Settings.Servers servers;
	protected Settings.Mirrors mirrors;
	protected Settings.Profiles profiles;
	protected Settings.ActiveProfiles activeProfiles;
	protected Settings.PluginGroups pluginGroups;

	/**
	 * Gets the value of the localRepository property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLocalRepository()
	{
		return localRepository;
	}

	/**
	 * Sets the value of the localRepository property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLocalRepository(String value)
	{
		this.localRepository = value;
	}

	/**
	 * Gets the value of the interactiveMode property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isInteractiveMode()
	{
		return interactiveMode;
	}

	/**
	 * Sets the value of the interactiveMode property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setInteractiveMode(Boolean value)
	{
		this.interactiveMode = value;
	}

	/**
	 * Gets the value of the usePluginRegistry property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isUsePluginRegistry()
	{
		return usePluginRegistry;
	}

	/**
	 * Sets the value of the usePluginRegistry property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setUsePluginRegistry(Boolean value)
	{
		this.usePluginRegistry = value;
	}

	/**
	 * Gets the value of the offline property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isOffline()
	{
		return offline;
	}

	/**
	 * Sets the value of the offline property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setOffline(Boolean value)
	{
		this.offline = value;
	}

	/**
	 * Gets the value of the proxies property.
	 * 
	 * @return possible object is {@link Settings.Proxies }
	 * 
	 */
	public Settings.Proxies getProxies()
	{
		return proxies;
	}

	/**
	 * Sets the value of the proxies property.
	 * 
	 * @param value
	 *            allowed object is {@link Settings.Proxies }
	 * 
	 */
	public void setProxies(Settings.Proxies value)
	{
		this.proxies = value;
	}

	/**
	 * Gets the value of the servers property.
	 * 
	 * @return possible object is {@link Settings.Servers }
	 * 
	 */
	public Settings.Servers getServers()
	{
		return servers;
	}

	/**
	 * Sets the value of the servers property.
	 * 
	 * @param value
	 *            allowed object is {@link Settings.Servers }
	 * 
	 */
	public void setServers(Settings.Servers value)
	{
		this.servers = value;
	}

	/**
	 * Gets the value of the mirrors property.
	 * 
	 * @return possible object is {@link Settings.Mirrors }
	 * 
	 */
	public Settings.Mirrors getMirrors()
	{
		return mirrors;
	}

	/**
	 * Sets the value of the mirrors property.
	 * 
	 * @param value
	 *            allowed object is {@link Settings.Mirrors }
	 * 
	 */
	public void setMirrors(Settings.Mirrors value)
	{
		this.mirrors = value;
	}

	/**
	 * Gets the value of the profiles property.
	 * 
	 * @return possible object is {@link Settings.Profiles }
	 * 
	 */
	public Settings.Profiles getProfiles()
	{
		return profiles;
	}

	/**
	 * Sets the value of the profiles property.
	 * 
	 * @param value
	 *            allowed object is {@link Settings.Profiles }
	 * 
	 */
	public void setProfiles(Settings.Profiles value)
	{
		this.profiles = value;
	}

	/**
	 * Gets the value of the activeProfiles property.
	 * 
	 * @return possible object is {@link Settings.ActiveProfiles }
	 * 
	 */
	public Settings.ActiveProfiles getActiveProfiles()
	{
		return activeProfiles;
	}

	/**
	 * Sets the value of the activeProfiles property.
	 * 
	 * @param value
	 *            allowed object is {@link Settings.ActiveProfiles }
	 * 
	 */
	public void setActiveProfiles(Settings.ActiveProfiles value)
	{
		this.activeProfiles = value;
	}

	/**
	 * Gets the value of the pluginGroups property.
	 * 
	 * @return possible object is {@link Settings.PluginGroups }
	 * 
	 */
	public Settings.PluginGroups getPluginGroups()
	{
		return pluginGroups;
	}

	/**
	 * Sets the value of the pluginGroups property.
	 * 
	 * @param value
	 *            allowed object is {@link Settings.PluginGroups }
	 * 
	 */
	public void setPluginGroups(Settings.PluginGroups value)
	{
		this.pluginGroups = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="activeProfile" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class ActiveProfiles
	{

		protected List<String> activeProfile;

		/**
		 * Gets the value of the activeProfile property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the activeProfile property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getActiveProfile().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link String }
		 * 
		 * 
		 */
		public List<String> getActiveProfile()
		{
			if (activeProfile == null)
			{
				activeProfile = new ArrayList<String>();
			}
			return this.activeProfile;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="mirror" type="{http://maven.apache.org/SETTINGS/1.0.0}Mirror" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Mirrors
	{

		protected List<Mirror> mirror;

		/**
		 * Gets the value of the mirror property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the mirror property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getMirror().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Mirror }
		 * 
		 * 
		 */
		public List<Mirror> getMirror()
		{
			if (mirror == null)
			{
				mirror = new ArrayList<Mirror>();
			}
			return this.mirror;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="pluginGroup" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class PluginGroups
	{

		protected List<String> pluginGroup;

		/**
		 * Gets the value of the pluginGroup property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the pluginGroup property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getPluginGroup().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link String }
		 * 
		 * 
		 */
		public List<String> getPluginGroup()
		{
			if (pluginGroup == null)
			{
				pluginGroup = new ArrayList<String>();
			}
			return this.pluginGroup;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="profile" type="{http://maven.apache.org/SETTINGS/1.0.0}Profile" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Profiles
	{

		protected List<Profile> profile;

		/**
		 * Gets the value of the profile property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the profile property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getProfile().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Profile }
		 * 
		 * 
		 */
		public List<Profile> getProfile()
		{
			if (profile == null)
			{
				profile = new ArrayList<Profile>();
			}
			return this.profile;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="proxy" type="{http://maven.apache.org/SETTINGS/1.0.0}Proxy" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Proxies
	{

		protected List<Proxy> proxy;

		/**
		 * Gets the value of the proxy property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the proxy property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getProxy().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Proxy }
		 * 
		 * 
		 */
		public List<Proxy> getProxy()
		{
			if (proxy == null)
			{
				proxy = new ArrayList<Proxy>();
			}
			return this.proxy;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="server" type="{http://maven.apache.org/SETTINGS/1.0.0}Server" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class Servers
	{

		protected List<Server> server;

		/**
		 * Gets the value of the server property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
		 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the server property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getServer().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Server }
		 * 
		 * 
		 */
		public List<Server> getServer()
		{
			if (server == null)
			{
				server = new ArrayList<Server>();
			}
			return this.server;
		}

	}

}
